template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "uppe1437"
__REPO__ = "lang-tau"
__UND2C__ = "tau"
__UNDEFINED__ = "Upper Tanana"
__UND__ = "tau"
