[package]
name = "tau"
human_name = "Upper Tanana"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.tau]
filename = "tau-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-tau"
platform = "windows"
uuid = "C3361F3B-4D16-4B28-8661-C77F335066D9"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.tau"
package = "speller-tau"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-tau-mso"
platform = "windows"
uuid = "0B2EDA2C-A572-48D7-9DD0-54DE9F17670C"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-tau"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
